services:

  api:
    build: .
    expose:
      - "3000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    networks:
      - shopsphere-network

  postgres:
    image: postgres:17
    container_name: shopsphere-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: shopsphere
    volumes:
      - shopsphere-postgres-data:/var/lib/postgresql/data
    networks:
      - shopsphere-network
  redis:
    image: redis:7-alpine
    container_name: shopsphere-redis
    networks:
      - shopsphere-network
  nginx:
    image: nginx:alpine
    container_name: shopsphere-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - shopsphere-network
volumes:
  shopsphere-postgres-data:

networks:
  shopsphere-network: